spring:
  config:
    import: optional:env[.env]
  application:
    name: grocey-api
  datasource:
    url: jdbc:mysql://localhost:3306/grocey?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: sk020608!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발 중엔 update / 배포 시엔 validate 또는 none
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: never




  # 필요 시 (서버 포트)
  server:
    port: 8080

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: 3600000      # 1시간
  refresh-token-expiration-ms: 1209600000

