INSERT INTO allergy (allergy_name) VALUES ('Egg');
INSERT INTO allergy ( allergy_name) VALUES  ('Milk');
INSERT INTO allergy ( allergy_name) VALUES  ('Flour');
INSERT INTO allergy ( allergy_name) VALUES  ('Peach');
INSERT INTO allergy ( allergy_name) VALUES  ('Fish');
INSERT INTO allergy ( allergy_name) VALUES  ('Peanut');
INSERT INTO allergy ( allergy_name) VALUES  ('Walnut');
INSERT INTO allergy ( allergy_name) VALUES  ('Pork');
INSERT INTO allergy ( allergy_name) VALUES  ('Crustacean');
INSERT INTO allergy ( allergy_name) VALUES ('Shellfish');
INSERT INTO allergy ( allergy_name) VALUES ('Squid');
INSERT INTO allergy ( allergy_name) VALUES ('Soy');
